services:
  # Servicio del backend
  backend:
    build:
      context: ./backend-biblioteca # Ruta al directorio del backend
    container_name: backend-biblioteca-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mysql-db
    networks:
      - red-biblioteca
    env_file:
      - ./backend-biblioteca/.env

  # Servicio del frontend
  frontend:
    build:
      context: ./frontend-biblioteca
    container_name: frontend-biblioteca-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - red-biblioteca

  # Servicio de la base de datos MySQL
  mysql-db:
    image: mysql
    container_name: mysql-biblioteca-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bd_biblioteca
      MYSQL_USER: biblioteca
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red-biblioteca

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-biblioteca-container
    environment:
      PMA_HOST: mysql-biblioteca-container
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    networks:
      - red-biblioteca

volumes:
  db_data: # Volumen para almacenar los datos del contenedor de MySQL

networks:
  red-biblioteca:
    driver: bridge